### ISSUE TITLE
AM to PM doesn't work

### ISSUE THREAD

**Issue by Razlik** [GreatApo/GreatFit#10]
Hello,
I find out problem with transfering AM to PM at noon. I'am using 12-hours format in setting and once there is noon the watch face doesn't automatically transfer from AM to PM. But it works in the evening, transfer from PM to AM at midnight.

Is it some bug or watch / watchface setting problem?

Thanks.

**Comment by GreatApo** [comment]
I will integrate a refresh function to make sure that the change is done :)

**Comment by GreatApo** [comment]
Added a custom refresher: commit 1e7a2c5dd33314f96c27466b9bad42f7a1aa829e
