### ISSUE TITLE
Pressure (mmHg option)

### ISSUE THREAD

**Issue by EgorOA** [GreatApo/GreatFit#11]
Hi!
Make an option to display pressure in mmHg, please!
mmHg is more handy in usual life.
Thanx in advance!

**Comment by GreatApo** [comment]
Additionally, there are reports that pressure does not update.

**Comment by GreatApo** [comment]
Update bug was fixed: commit 22a1b5dc5c5ebb99006b723dc8af1dc0bce7099f

**Comment by GreatApo** [comment]
Units option added: commit 2e53641cd5dca72aee4f8c0e77f4e645ecf276e7
