### ISSUE TITLE
Month change to OCT

### ISSUE THREAD

**Issue by Kookie69** [GreatApo/GreatFit#12]
Hi Guys love your watchface works great but this morning with the change to OCT it now shows 10 and a Chinese symbol instead and a 12 with Chinese symbol when the lock screen is on plus i have reset the watch and reinstalled the watchface with no change. I'm running Greatfit 3.5 on the latest OS international Stratos and yes the language is set to english thanks. 
![2018-10-01 08 59 12](https://user-images.githubusercontent.com/43732946/46263902-074c4400-c559-11e8-9c8d-69de812e1920.jpg)

**Comment by tympapost** [comment]
I'm having an issue which is 99% related to this.
After the date changed to October, when the watch is on standby mode (locked) it shows "Dec" (in greek) but when I unlock it, it shows "Oct" as expected.
I hope this helps to tackle with this issue.

**Comment by djalex29** [comment]
I have exactly the same problem. And now the date changes to December when the screen is locked. This happens to all apk watchface, not only with greatfit

**Comment by djalex29** [comment]
Firmware STRATOSfied rel 18, Version 2.0.37.0

**Comment by Kookie69** [comment]
Ok thanks for letting me know appreciated.

**Comment by TehZommbie** [comment]
I have the same issue as OP. Also, if I disable month as text, month shows up as 10 (correctly) when unlocked but when locked it shows 0. @GreatApo has already posted on XDA stating he is working on this.

**Comment by GreatApo** [comment]
Already fixed in commits:
@126cadf6a2c7142121aa8e04faa8dd65958cf461 and @3839b94c8575bcc14c2b1ed1809cb011283f4472
