### ISSUE TITLE
"World Time" Widget

### ISSUE THREAD

**Issue by JanosAudron** [GreatApo/GreatFit#16]
If you enable the widget "World Time" while the setting "Always am/pm" is off the whole watchface crashes. Some more info, Amazfit Pace with stock US rom 2.8.1.0, italian language set into watchface settings, time format 24-hour.

**Comment by GreatApo** [comment]
Except from the reported problems, some more improvements where requested for this feature:

A more stable global timer displaying standard UTC/GMT

Example:
 ![](https://i.imgur.com/54J0Fjr.jpg)

**Comment by GreatApo** [comment]
I didn't notice any crashes in the latest code state, so I am reporting the lattest updates/fixes on this feature in general:
- World time proper SLPT update fixed
- Now is based on GMT zones

Commits 9974f3a82bc944c4e2ff4e4f77beade5a469779c , d56e1c6fe1651bdae852ba8bff0bac9580c768fe
