### ISSUE TITLE
layering widgets

### ISSUE THREAD

**Issue by mcconkiee** [GreatApo/GreatFit#20]
i love the work you've been doing @GreatApo ! It's given me the headstart to get involved in watch faces. I'm doing my first, a  ~~shamless rip off~~ inspiration from the HR Steel design. My issue is the analog hands are under the widget. I've followed the same pattern on my custom clock face, making both the heart rate and power (lower tachometer) widgets - each subscribing to their appropriate `DataType`. Everything is working except for this layering. 

here is how they are implemented on my extended `AbstractWatchFace` class:

```
@Override
    public void onCreate() {
        context = this.getApplicationContext();

        // Load settings
        Settings settings = new Settings();

        this.clock = new MainClock(settings);
        this.widgets.add(new TachWidget(settings));
        this.widgets.add(new TopWidget(settings));

        super.onCreate();
    }
```

If you look closely, the top widget is above the hands. That widget is only the icon and text:

![img_20181102_070011](https://user-images.githubusercontent.com/1483397/47931560-6371f300-de8c-11e8-990b-78a2d4a8681b.jpg)

...ha, that's my dog i just noticed in the background ^^ LOL

**Comment by GreatApo** [comment]
It's because the widget are created after the main clock.

You can change the creation order or  make a new widget with the hour/minute hands that will always be at the end.
