### ISSUE TITLE
Crash with change of month to Dec

### ISSUE THREAD

**Issue by Kookie69** [GreatApo/GreatFit#22]
Hi 30 mins into Dec here in Sydney and i have noticed this watchface and 1 other apk watchface i have both crash when i select them so i.m thinking it has something to do with the change of month as it did work perfect thanks.

**Comment by GreatApo** [comment]
I will find out in 5 hours :P

**Comment by ravenodessa** [comment]
Confirm. The GreatFit is not crash with error after 30th November.

**Comment by GreatApo** [comment]
Commit cabedb45dad0de2d8cd7292254a46770498f5102

Install the new version!
