### ISSUE TITLE
Spacing between hours and minutes

### ISSUE THREAD

**Issue by NunoMPG** [GreatApo/GreatFit#23]
The second digit in the hours and the first digit in the minutes have no spacing between them. For example, when is 08:00 the eight and the zero (first digit of minutes) are touching
Please see attached image

![img_20181206_080550_hht](https://user-images.githubusercontent.com/3594923/49704605-f54be900-fc0c-11e8-8e8f-745dd8187480.jpg)

**Comment by rufik** [comment]
Yes, it's clearly visible with 24-hour clock and digits like 0 or 8.

**Comment by rufik** [comment]
Could someone point me to resource which is responsible for layout? I'd like to try some modifications about this issue...

**Comment by GreatApo** [comment]
+2px distance between was added. I will test it and adjust it further.

commit d8ebfa879c3dace9efb3856af82518a2ff89f512

**Comment by rufik** [comment]
I've tested v3.9 beta - it' better, but still not perfect :) I took these 2 screenshot to show layout with "fat" and "slim"digits. As you can see, **09:30** is still too close to each other. "**09:31**" is perfect I think.

![pace_greatfit_3 9](https://user-images.githubusercontent.com/425558/58155869-16613d00-7c75-11e9-89c9-9e527a92b0a5.jpg)
