### ISSUE TITLE
Amazfit Verge Support

### ISSUE THREAD

**Issue by GreatApo** [GreatApo/GreatFit#24]
Amazfit Verge has a 360x360 resolution screen. GreatFit should:
- detect the screen
- adjust the style (or use a second style)

**Comment by skorokithakis** [comment]
This is the best face I've found so far, and it's a pity that it doesn't work with the Verge. Please let me know if you need me to run some tests or otherwise help out with Verge support.

**Comment by fgrassmann** [comment]
I think sensors interface has also to be reworked, as (for example) the air pressure is not displayed on the Verge.

**Comment by GreatApo** [comment]
First step was done. The interface was scaled to match Verge. All watches share the same source code (!) and only the libraries need to change.

Commit a63eb01a2402822f03711847153d93ab375949b7

**Comment by GreatApo** [comment]
I think we are done! up to the following commit a2dec5988a16dd144a68066ddea60e2e1b4a9965 Verge version seems a little stable.

**Comment by GreatApo** [comment]
There are currently problems with:
- Custom data updating (normal screen)
- Heart rate

**Comment by skorokithakis** [comment]
Is there a release so I can test this, or do I need to compile it?

**Comment by skorokithakis** [comment]
Hmm the graphics are all bunched up, as if designed for a smaller screen with that beta apk.

**Comment by GreatApo** [comment]
Your watch was probably not recognized as Verge. I changed the identification code to match product name some hours ago. I think only the Heart Rate is not properly working.

Universal Pace/Stratos/Verge version!
[GreatFit.3.9.Beta.apk.zip](https://github.com/GreatApo/GreatFit/files/3204984/GreatFit.3.9.Beta.apk.zip)

**Comment by fgrassmann** [comment]
What do you mean by this? Heart rate widget seems to show a reasonable value over here.

**Comment by skorokithakis** [comment]
This works great for me, except I've set "show only clock on sleep" and it still shows the entire face, not even with my configuration. It shows steps and other things, even though I've removed them. Do I need to clear preferences?

**Comment by GreatApo** [comment]
> What do you mean by this? Heart rate widget seems to show a reasonable value over here.
Heart rate doesn't work for me on Verge.


> This works great for me, except I've set "show only clock on sleep" and it still shows the entire face, not even with my configuration. It shows steps and other things, even though I've removed them. Do I need to clear preferences?
It just needs to click the save button. Strange behavior, however I have't figure out where a bug showing wrong things in slpt is coming from (libs problem).

**Comment by skorokithakis** [comment]
> It just needs to click the save button

It works fine when showing the face, it's the sleep display that's wrong. That's too bad, I love the face otherwise.

**Comment by skorokithakis** [comment]
Rebooting fixes the sleep bug (it shows the right things on the screen).

**Comment by GreatApo** [comment]
I think we are done. There is still the bug showing 2 widgets one over the other, however, it is not limited on Verge.

Done, commit 64c17e976fca53d754c7b79e8509623e7f3664eb
