### ISSUE TITLE
More weather data

### ISSUE THREAD

**Issue by GreatApo** [GreatApo/GreatFit#28]
Forward more weather data with Amazmod:
- Sunrise
- Sunset
- Moon phase
- Tide
- Visibility
- Air quality

An idea is to pull some data from [this API](https://openweathermap.org/).

**Comment by GreatApo** [comment]
+ update weather/temperature/city from Google weather notifications

**Comment by GreatApo** [comment]
moon phase also requested

**Comment by GreatApo** [comment]
Amazmod has now integrated [KieronQuinn's AmazfitInternetCompanion](https://github.com/KieronQuinn/AmazfitInternetCompanion) and it will be easier to get the data above.

Mind that moon phase is already integrated by AndreaOmodeo

**Comment by lfom** [comment]
AFAIK air quality is also provided by Huami, but I am not sure if the data is available outside China.

**Comment by GreatApo** [comment]
> AFAIK air quality is also provided by Huami, but I am not sure if the data is available outside China.

If I remember correctly, data are included in Huami's weather app are not populated. Thus, you must be correct.

**Comment by GreatApo** [comment]
The following new widgets where added. Latest bleeding edge Amazmod version is needed along with its custom weather.
- Sunrise
- Sunset
- Visibility
- Clouds

Commit 2c5be1d512ad895ba46a459c98f528cf26fd9252

Current issue will close as most requested widgets are already scripted.
