### ISSUE TITLE
Analog Clock

### ISSUE THREAD

**Issue by danireo** [GreatApo/GreatFit#31]
Thanks for the great work! I added Bulgarian language and tried to implement MainClockAnalog. It works, but when I try to open Settings on my watch it crashes. I've commented "Settings section" in the code and it works without using any widgets. Please take a look I'd be really happy to see it working
[MainClockAnalog.txt](https://github.com/GreatApo/GreatFit/files/2683594/MainClockAnalog.txt)

.

**Comment by GreatApo** [comment]
Awesome!

**Comment by danireo** [comment]
I've done it, but it's quite buggy on STRATOSfied 2.0.46.0 
[Uploading preview.png…]()

[GreatFit-3.7Test.zip](https://github.com/GreatApo/GreatFit/files/2684649/GreatFit-3.7Test.zip)

**Comment by GreatApo** [comment]
Danireo, thank you very much for your code, it was very helpful!

Commit 1709ad5067021b4c531eab2075d874e9cccdd20a
