### ISSUE TITLE
Stratos 2.3.8.0 - watch crash

### ISSUE THREAD

**Issue by Kookie69** [GreatApo/GreatFit#34]
Hi All
Have the lattest version installed and it does still crash my watch within an hour or so of loading it as the current watchface sorry to say.

**Comment by Kookie69** [comment]
Using the current Stratos OS 2.3.8.0 and running amazmob and the calendar plus a number of apk watchfaces all working perfect exept for greatfit all versions 3.7 and 3.7 beta and 3.8 and yes i have factory reset the watch each time after greatfit caused the crash when it went into lock mode so not sure if i'm the only 1.

**Comment by GreatApo** [comment]
What widgets are you using?

**Comment by GreatApo** [comment]
I mean on GreatFit...

**Comment by domsle** [comment]
I have the same problem. After initial few seconds of watchface working I
see crash of WearServices.
Widgets that I have: weather, calories hearth rate, phone battery and
notifications. On circular bar I have watch battery.

niedz., 20 sty 2019, 13:43: Grammatopoulos Apostolos <
notifications@github.com> napisał(a):

**Comment by GreatApo** [comment]
@domsle seconds on?

I am trying to spot the differences because I have the same setup with no problem :/

**Comment by GreatApo** [comment]
Seconds on is not working. Please verify that this is the problem for you too.

**Comment by domsle** [comment]
Doesn't make any difference, either way it crashes.

niedz., 20 sty 2019, 14:36: Grammatopoulos Apostolos <
notifications@github.com> napisał(a):

**Comment by Kookie69** [comment]
Never have used the second hands uses to much power so can't be my issue I guess.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Kookie69** [comment]
Hi Just wonder why the thread was changed to seconds causing the crash when i don't use the seconds on the watchface and never have so not sure how it's related to my case but keep up the good work by the way :)

**Comment by GreatApo** [comment]
Sorry I changed it before you confirming

**Comment by Kookie69** [comment]
All good was just wondering that all thanks 😊

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by GreatApo** [comment]
I can't replicate the crash 😢 
Can I have an error log?

**Comment by Kookie69** [comment]
The watch has been reset twice since the crash would the error log still be intact I’m thinking not my self plus now I’m starting to wonder if my watch is actually faulty as this afternoon at work I caught the watch draining about 10% in 2 hours for no reason all I did today was 25K or so steps and a couple of weeks ago it did it as well with the old FW 2.3.7.0 didn’t wear it over night and from about 80% went to bed to totally flat in the morning and never did it again till today but a reboot seems to have stopped the massing drain so maybe my next thing to do is flash the rom to see if that help if not it’s going in the bin a bit over really.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by GreatApo** [comment]
Many users have these strange battery drains 👎 and they are almost random. There is a good post on facebook about how to address them.

The crashes are mostly related with our hacked apks and are difficult to replicate and fix them sometimes.

**Comment by Kookie69** [comment]
Think i might have narrowed it down to 3 possible APK watchfaces that may have been causing Greatfit to crash the watch and they are all modded MZI watchfaces that i downloaded from Amazfitwatchfaces.com but crossing my fingers Greatfit is still up and running with out those watchfaces installed.

**Comment by GreatApo** [comment]
I can't replicate it 😞

**Comment by Kookie69** [comment]
Perhaps the Error log may help you as I didn’t reset the watch after the last 2x times I crashed it if you can tell me where to find it I can get it for you.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by GreatApo** [comment]
1. Install ADB (google it!)
2. Shift+right click on descktop and select open PowerShell here (provided you are on windows 10)
3. Connect your watch to PC
4. Write on the console this command and press Enter:
``adb logcat -d > logcat.txt``

**Comment by Kookie69** [comment]
[logcat.txt](https://github.com/GreatApo/GreatFit/files/2800472/logcat.txt)
Here is the log hope it can help.

**Comment by GreatApo** [comment]
There is no GreatFit error it this log not even a try to set as watchface. Please encounter the error and then pull the log without restarting 👍

**Comment by Kookie69** [comment]
Ok will do now will have it for you shortly.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Kookie69** [comment]
[logcat.txt](https://github.com/GreatApo/GreatFit/files/2800578/logcat.txt)
Yep got it to crash and lifted the log while crashed so hope this might show something.

**Comment by Kookie69** [comment]
Just an update the same crash issue is still there with the OS 2.3.9.0 update and i did reset after the update sorry to say.

**Comment by Kookie69** [comment]
I don't give up on a good thing easily i finally found a way to stop the watchface crashing on my Stratos by changing widget 3 from phone battery level to Floors and that has stopped the crashes so it does seem to be a widget related issue.

**Comment by Kookie69** [comment]
I decided to give the modded versions of Greatfit a try both the black background and white background version and both work fine and i can't get them to crash so there must be a difference between the Stock version that i prefer the best and the modded versions maybe worth looking at.
