### ISSUE TITLE
Add distance traveled widget based on steps

### ISSUE THREAD

**Issue by GreatApo** [GreatApo/GreatFit#36]
Knowing the height of the user (and approximate average step length) or the average step length, the distance traveled can be calculated from steps.

**Comment by Kookie69** [comment]
This would be awesome as found it very weird that the Stratos never had distance for steps like every other smartwatch has only when doing an activity thats it love your work :)

**Comment by carlosDigio** [comment]
+1. Please, I NEED this feature. I bought the Stratos thinking that it would show the daily distance and it was a disappointment to discover that it does not take it :____(

**Comment by GreatApo** [comment]
There is already a [pull request](https://github.com/GreatApo/GreatFit/pull/51) providing this feature by alvaroDigio.

This issue will close after the integration.

**Comment by GreatApo** [comment]
Done, commint 0868bcd0774b39579a265832ceac9a9a81164fc9

**Comment by Kookie69** [comment]
Hi love your work and I find the Version 4.0 on my Stratos is working great and stable but can you tell me when is this updated version with the daily steps distance going to be released thanks again.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by GreatApo** [comment]
It will be released in the following days
