### ISSUE TITLE
Crash when turn on notification wirdget

### ISSUE THREAD

**Issue by sartyukhov** [GreatApo/GreatFit#40]
Hello!
After installation i can set Widget 5 to "Notifications".
But after, if I change some settings in "Other features" it crashes down. 
Working only if notification widget not used.

For example widgets for crash:
1- weather Icon
2- steps
3- watch alarm 
4- battery %%
5- Notifications 
Bar - Steps

Features:
resolution +
flashing - 
month txt +
3 letters month +
3 letters day +
No 0 + 
wind as arrows -
show status bar - 
animate - 
always am/pm - 

Official firmware 2.3.9.0 (Startos)

**Comment by sartyukhov** [comment]
I've detected, when notifications non empty it works well, when it's empty -> crash

**Comment by GreatApo** [comment]
I can't replicate the problem (at least with the latest amazmod), however, I am monitoring it.
