### ISSUE TITLE
Calories icon not shown in slpt screen

### ISSUE THREAD

**Issue by SantiLlompart** [GreatApo/GreatFit#45]
When watch goes to slpt mode, the calories icon is not drawn. But if you select battery widget and calories widget, in slpt mode calories icon is drawn.
In line 166 of
app/src/main/java/com/dinodevs/greatfitwatchface/widget/CaloriesWidget.java 
Now is: if (settings.battery_percentIcon) {
Must be:  if (settings.CaloriesIcon) {

Making this change, calories icon will be drawn always

**Comment by GreatApo** [comment]
Too much copy paste... Thanks!

Fixed: commit 6f7acbe04167cfcece48db404f4f1e2b9031588b
