### ISSUE TITLE
SLPT moon changes when Hicolor is activated

### ISSUE THREAD

**Issue by AndreaOmodeo** [GreatApo/GreatFit#46]
Hello, I'm the author of the MoonPhase widget.
When the watch is in low-power SLPT, I actually see app\src\main\assets\slpt_moon\moon5.png.
But when I twist the wrist , better_resolution mode is activated and the displayed icon becomes app\src\main\assets\26wc_moon6.png.

At least this is what I see, but I cannot understand how this is possible, since the line of code is very straightforward:
String filename = (better_resolution) ? String.format("26wc_moon/moon%d.png", i) : String.format("slpt_moon/moon%d.png", i);

I don't have an explaination, unless the committed source code is different from the beta build you released.

**Comment by GreatApo** [comment]
No you are correct, that is why it works here :P

Except from the last commit I just made, the released version reflects the source code :)

**Comment by AndreaOmodeo** [comment]
I've made a video to show the situation.
https://youtu.be/1y7SYYktcBI
moon icon is Widget 5, you can see it changes when hicolor mode is activated.

I've downloaded the APK from your post on XDA. Should I build it by myself?

**Comment by GreatApo** [comment]
Video is not loading yet, I will try later too.

I think I understood what you are saying. Try installing the latest release: https://github.com/GreatApo/GreatFit/releases

You can also build the sources by yourself, whatever feels better your you :)

**Comment by GreatApo** [comment]
Video is still not available, however it doesn't matter so much since you have described the weird behavior. I will have a look again in the problem before closing the issue.
