### ISSUE TITLE
Total distance not showing

### ISSUE THREAD

**Issue by sq4ind** [GreatApo/GreatFit#5]
Total distance not showing when choosen to be displayed in any of the widgets.

**Comment by GreatApo** [comment]
I had completely forgot to initialize the code of the widgets ^_^
Fixed on commit d52d994368c7f220c5c44823ad7412e11f2d709b

I also fixed the units not showing when screen is on for both daily/total distance widgets.
Commit 1365ea804d2340e49a11a04a30e36116cc5f0490
