### ISSUE TITLE
AM/PM display disable

### ISSUE THREAD

**Issue by sq4ind** [GreatApo/GreatFit#6]
It would be nice to have an option to disable display of AM/PM

**Comment by GreatApo** [comment]
Completely or just when 24h time type is on?

**Comment by GreatApo** [comment]
Option added to disable AM/PM when time format is 24h.
Commit 6588e23c06906d61710a727720ad64a73fe1ca0e

Can it be closed?

**Comment by sq4ind** [comment]
Yes can be closed.

Compiles apk myself installed. It's perfect. Thanks for such a quick fix.
