### ISSUE TITLE
After finished workout, not getting clock displayed

### ISSUE THREAD

**Issue by sq4ind** [GreatApo/GreatFit#7]
after the workout is finished I am not getting the clock, but workout paused screen (when locked). when unlocked it's fine

**Comment by lfom** [comment]
Did you restart the watch after installing APK? What is the firmware version installed on watch? This may happen if you have the wrong version installed for your firmware too...

**Comment by GreatApo** [comment]
This was a bug in GreatFit versions 3.1 and lower. Do you have the latest version installed?

**Comment by sq4ind** [comment]
I think it was a glitch. Working fine now.
