### ISSUE TITLE
Disable seconds on standby but enable while unlocked or hand risen

### ISSUE THREAD

**Issue by dtsd** [GreatApo/GreatFit#79]
Showing seconds is useful but eats up too much battery. Some watch faces shows seconds when unlocked. Can we do this also? Even better would be showing seconds when raising hand.

**Comment by zdunex25** [comment]
This is switchable feature, just disable it.

**Comment by dtsd** [comment]
> This is switchable feature, just disable it.

There's "second hand" option, that completely disables or enables seconds. I ask for third mode, disabled on standby and enabled when unlocked or hand rise

**Comment by zdunex25** [comment]
Second hand available from watch settings controls SLPT mode only, disabling Second hand does not affect unlocked mode.

**Comment by dtsd** [comment]
> Second hand available from watch settings controls SLPT mode only, disabling Second hand does not affect unlocked mode.

I'm on Stratos 2.3.13 stock firmware rumming app version 4.1. I see no app config for seconds. Second hand from OS watch settings controls seconds appeance in app in every mode.

**Comment by zdunex25** [comment]
It's weird it does not work for me like this.
See here seconds are enabled by default (in unlocked mode) and you cannot disable them with "Second hand" setting on the watch: https://github.com/GreatApo/GreatFit/blob/master/app/src/main/java/com/dinodevs/greatfitwatchface/widget/MainClock.java#L281

**Comment by dtsd** [comment]
That's because line You reference was changed this year and 4.1 was released the year before. Are there any other newer builds?
