### ISSUE TITLE
Month as text not working propertly on locked screen

### ISSUE THREAD

**Issue by Rdzeniuch** [GreatApo/GreatFit#8]
When i set up month as text, when unlocked it works fine but when i lock it, it shows only 3 letters of month. (In Polish language)

**Comment by Rdzeniuch** [comment]
![img_20180903_212413](https://user-images.githubusercontent.com/16858207/44999769-ec20ff80-afbf-11e8-85ac-1aa4923f9578.jpg)
![img_20180903_212352](https://user-images.githubusercontent.com/16858207/44999770-ecb99600-afbf-11e8-9e0a-8009bc9810bc.jpg)

**Comment by GreatApo** [comment]
You are right! I was not aware of that, thanks for reporting.

Fixed on commit 7900d6997b2b4f0429e4e62f05e1208a3d37e195
